reviews/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'reviews'
#型指定可能
urlpatterns = [
    path('review/', views.review_list,name = 'review_list'),
    path('wine/', views.wine_list, name='wine_list'),
    path('wine/<int:wine_id>/',views.wine_detail,name = 'wine_detail'),
    path('wine/<int:wine_id>/<int:review_id>',views.review_detail_of_wine,name = 'review_detail_of_wine'),
    path('wine/<int:wine_id>/add_review', views.add_review, name='add_review'),
    path('user/<username>/',views.user_review_list, name = 'user_review_list'),
    path('recommendation/',views.user_recommendation_list, name = 'user_recommendation_list')
]

winereview/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/',include('reviews.urls', namespace = 'reviews')),
    path('accounts/',include('registration.backends.simple.urls')),
    path('accounts/',include('django.contrib.auth.urls',namespace = 'auth'))
]

reviews/models.py
from django.db import models
import numpy as np
from django.contrib.auth.models import User

# Create your models here.

class Wine(models.Model):
    name = models.CharField(max_length = 128)

    def average_rating(self):
        all_ratings = list(map(lambda x:x.rating,self.review_set.all()))
        return np.mean(all_ratings)

    def __str__(self):
        return self.name

class Review(models.Model):

    RATING_CHOICES = (
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
    )

    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(verbose_name='date_published')
    user_name = models.CharField(max_length = 100)
    comment = models.CharField(max_length = 200)
    rating = models.IntegerField(choices = RATING_CHOICES)

    def __str__(self):
        return self.comment

class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
          'comment':Textarea(attrs = {'cols':40, 'rows':15})
        }

reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Wine, Review, Cluster
from .forms import ReviewForm
import datetime

from django.contrib.auth.models import User

from .suggestions import update_clusters
# Create your views here.

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)

def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list': wine_list}
    return render(request,'reviews/wine_list.html',context)

def wine_detail(request, wine_id): #given from urls
    wine = get_object_or_404(Wine, pk = wine_id)
    context = {'wine':wine}
    return render(request, 'reviews/wine_detail.html',context)

def review_detail_of_wine(request, wine_id, review_id):
    wine = get_object_or_404(Wine, pk = wine_id)
    review = get_object_or_404(wine.review_set.all(), pk = review_id)
    return render(request, 'reviews/review_detail_of_wine.html', {'review':review})

@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        #user_name = form.cleaned_data['user_name']
        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))

    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})

@login_required
def user_recommendation_list(request):
     user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('wine')
     # from the reviews, get a set of wine IDs
     user_reviews_wine_ids = set(map(lambda x: x.wine.id, user_reviews))
     # then get a wine list excluding the previous IDs
     try:
        user_cluster_name = \
            User.objects.get(username=request.user.username).cluster_set.first().name
     except: # if no cluster has been assigned for a user, update clusters
         update_clusters()
         user_cluster_name = \
             User.objects.get(username=request.user.username).cluster_set.first().name

    # get usernames for other memebers of the cluster
     user_cluster_other_members = \
         Cluster.objects.get(name=user_cluster_name).users \
             .exclude(username=request.user.username).all()
     other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    # get reviews by those users, excluding wines reviewed by the request user
     other_users_reviews = \
         Review.objects.filter(user_name__in=other_members_usernames) \
             .exclude(wine__id__in=user_reviews_wine_ids)
     other_users_reviews_wine_ids = set(map(lambda x: x.wine.id, other_users_reviews))

    # then get a wine list including the previous IDs, order by rating
     wine_list = sorted(
         list(Wine.objects.filter(id__in=other_users_reviews_wine_ids)),
         key=lambda x: x.average_rating(),
         reverse=True
     )

     return render(
         request,
         'reviews/user_recommendation_list.html',
         {'username': request.user.username,'wine_list': wine_list}
     )

#render user's own reviews
def user_review_list(request,username = None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name = username).order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list,'username':username}
    return render(request, 'reviews/user_review_list.html', context)

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav  class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Wine Reviews</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:wine_list' %}">Wine List</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'reviews:user_recommendation_list' %}">
                  Wine suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href = "/accounts/register">Sign up</a></li>
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

templates/reviews/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav  class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Wine Reviews</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:wine_list' %}">Wine List</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

templates/reviews/review_detail_of_wine.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>
{% endblock %}


{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

templates/reviews/review_list.html
{% extends 'base.html' %}

{% load bootstrap3%}

{%bootstrap_css%}
{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:wine_detail' review.wine.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

templates/reviews/review_of_wine.html
{% extends 'reviews/base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>Review Detail</h2>
{% endblock %}

{% block content %}
  {{wine.name}}
{% endblock %}

templates/reviews/user_recommendation_list.html
{%extends 'reviews/wine_list.html'%}

{%block title%}
<h2>Recommendation list for {{username}}</h2>
{%endblock%}

templates/reviews/user_review_list.html
{%extends 'reviews/review_list.html'%}

{%block title%}
 <h2> Reviews by {{username}} </h2>
{%endblock%}

templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div class="row">
    {% for review in wine.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail_of_wine' wine.id review.id %}" class = reviewlink>
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {{form}}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

templates/reviews/wine_list.html
{% extends 'base.html' %}

{% load bootstrap3%}
{% bootstrap_css %}

{% block title %}
<h2>Wine List</h2>
{% endblock %}

{% block content %}
{% if wine_list %}
<div>
    {% for wine in wine_list %}
    <div>
        <h4><a href = "{% url 'reviews:wine_detail' wine.id%}">
          {{wine.name}}</a></h4>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No wines are available.</p>
{% endif %}
{% endblock %}